package(default_visibility = ["//visibility:public"])

load("//tools/build_defs/skylark:skylark.bzl", "skylark_library")

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
)

skylark_library(
    name = "skylark",
    srcs = ["skylark.bzl"],
)
