package(default_visibility = ["//visibility:public"])

py_library(
    name = "stubs",
    srcs = [
        "attr.py",
        "skylark_globals.py",
    ],
    deps = [
        "//src/main/protobuf:build_pb_py",
    ],
)
