load("/tools/build_rules/rust", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "hello_lib",
    srcs = [
        "src/greeter.rs",
        "src/lib.rs"
    ],
)
